-- Run these SQL commands in your Supabase SQL Editor to set up the necessary tables

-- 1. Members Table
create table public.members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text,
  phone text,
  membership_type text default 'Basic',
  status text default 'Active',
  join_date date default CURRENT_DATE,
  last_visit date default CURRENT_DATE,
  trainer text
);

-- 2. Classes Table
create table public.classes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  instructor text,
  schedule_time timestamp with time zone,
  capacity int default 20,
  enrolled int default 0,
  status text default 'Active',
  room text,
  type text,
  description text
);

-- 3. Equipment Table
create table public.equipment (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text,
  brand text,
  model text,
  location text,
  status text default 'operational', -- 'operational', 'maintenance', 'broken'
  last_maintenance date,
  next_maintenance date,
  condition text,
  serial_number text,
  purchase_date date,
  warranty date,
  notes text
);

-- 3.1 Trainers Table
create table public.trainers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text,
  phone text,
  specialization text,
  experience text,
  rating decimal default 5.0,
  status text default 'Active',
  location text,
  bio text,
  hourly_rate int
);

-- 4. Payments Table
create table public.payments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  amount decimal not null,
  member_id bigint references public.members(id),
  type text, -- 'membership', 'personal_training', 'product'
  status text default 'completed'
);

-- 5. Workout Plans Table
create table public.workout_plans (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  member_id bigint references public.members(id),
  description text
);

-- 6. Workout Exercises Table
create table public.workout_exercises (
  id bigint generated by default as identity primary key,
  plan_id bigint references public.workout_plans(id) on delete cascade,
  name text not null,
  sets int,
  reps int,
  weight text,
  notes text
);

-- Enable RLS (Row Level Security) - Simplified for this demo
alter table public.members enable row level security;
create policy "Enable all access for authenticated users" on public.members for all using (true);

alter table public.classes enable row level security;
create policy "Enable all access for authenticated users" on public.classes for all using (true);

alter table public.equipment enable row level security;
create policy "Enable all access for authenticated users" on public.equipment for all using (true);

alter table public.payments enable row level security;
create policy "Enable all access for authenticated users" on public.payments for all using (true);

alter table public.workout_plans enable row level security;
create policy "Enable all access for authenticated users" on public.workout_plans for all using (true);

alter table public.workout_exercises enable row level security;
create policy "Enable all access for authenticated users" on public.workout_exercises for all using (true);

alter table public.trainers enable row level security;
create policy "Enable all access for authenticated users" on public.trainers for all using (true);

-- 7. Attendance Table
create table public.attendance (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  member_id bigint references public.members(id),
  check_in timestamp with time zone default timezone('utc'::text, now()) not null,
  check_out timestamp with time zone,
  status text default 'present' -- 'present', 'absent', 'late'
);

alter table public.attendance enable row level security;
create policy "Enable all access for authenticated users" on public.attendance for all using (true);

-- 8. Membership Plans Table
create table public.membership_plans (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price decimal not null,
  duration text, -- '1 month', '3 months', 'annual'
  features text[], -- array of features
  status text default 'active'
);

alter table public.membership_plans enable row level security;
create policy "Enable all access for authenticated users" on public.membership_plans for all using (true);

-- 9. App Users (Profiles) Table
create table public.app_users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  username text not null,
  email text not null unique,
  role text default 'staff', -- 'owner', 'admin', 'manager', 'staff'
  status text default 'active',
  last_login timestamp with time zone,
  permissions text[] default '{}'
);

alter table public.app_users enable row level security;
create policy "Enable all access for authenticated users" on public.app_users for all using (true);

-- 10. System Logs Table
create table public.system_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  level text default 'info', -- 'info', 'warning', 'error'
  message text not null,
  user_name text,
  action text
);

alter table public.system_logs enable row level security;
create policy "Enable all access for authenticated users" on public.system_logs for all using (true);

-- Seed some initial admin data
insert into public.app_users (username, email, role, status, permissions) values 
('owner', 'owner@gympro.com', 'owner', 'active', '{"all"}'),
('admin', 'admin@gympro.com', 'admin', 'active', '{"all"}'),
('manager1', 'manager1@gympro.com', 'manager', 'active', '{"members", "classes", "trainers"}');

-- 11. System Settings Table
create table public.settings (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.settings enable row level security;
create policy "Enable all access for authenticated users" on public.settings for all using (true);

-- Initial fallback settings
insert into public.settings (key, value) values 
('gym_info', '{"gymName": "GymPro Fitness Center", "address": "123 Elite Street, Tech Park, City - 560001", "openTime": "05:00", "closeTime": "23:00", "capacity": "200", "website": "www.gympro.com"}'),
('app_preferences', '{"language": "English (US)", "currency": "INR (₹)", "dateFormat": "DD/MM/YYYY"}'),
('notifications', '{"emailAlerts": true, "smsAlerts": false, "marketing": true, "maintenanceReminders": true}');
