-- Run these SQL commands in your Supabase SQL Editor to set up the necessary tables

-- 1. Members Table
create table public.members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text,
  phone text,
  membership_type text default 'Basic',
  status text default 'Active',
  join_date date default CURRENT_DATE,
  last_visit date default CURRENT_DATE,
  trainer text
);

-- 2. Classes Table
create table public.classes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  instructor text,
  schedule_time timestamp with time zone,
  capacity int default 20,
  enrolled int default 0
);

-- 3. Equipment Table
create table public.equipment (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  status text default 'operational', -- 'operational', 'maintenance', 'broken'
  last_maintenance date
);

-- 4. Payments Table
create table public.payments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  amount decimal not null,
  member_id bigint references public.members(id),
  type text, -- 'membership', 'personal_training', 'product'
  status text default 'completed'
);

-- 5. Workout Plans Table
create table public.workout_plans (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  member_id bigint references public.members(id),
  description text
);

-- 6. Workout Exercises Table
create table public.workout_exercises (
  id bigint generated by default as identity primary key,
  plan_id bigint references public.workout_plans(id) on delete cascade,
  name text not null,
  sets int,
  reps int,
  weight text,
  notes text
);

-- Enable RLS (Row Level Security) - Simplified for this demo
alter table public.members enable row level security;
create policy "Enable all access for authenticated users" on public.members for all using (true);

alter table public.classes enable row level security;
create policy "Enable all access for authenticated users" on public.classes for all using (true);

alter table public.equipment enable row level security;
create policy "Enable all access for authenticated users" on public.equipment for all using (true);

alter table public.payments enable row level security;
create policy "Enable all access for authenticated users" on public.payments for all using (true);

alter table public.workout_plans enable row level security;
create policy "Enable all access for authenticated users" on public.workout_plans for all using (true);

alter table public.workout_exercises enable row level security;
create policy "Enable all access for authenticated users" on public.workout_exercises for all using (true);
